### ISSUE TITLE
Problem in class inheritance

### ISSUE THREAD

**Issue by deveshprojectwork** [deveshprojectwork/mydevops#1]
class name is not correct

**Comment by bipeensinha** [comment]
Hi Devesh , I try fix the problem bin inheritance was not blocked ut

**Comment by deveshprojectwork** [comment]
Once done please close it.

**Comment by bipeensinha** [comment]
ok thanks , pleasae you can close the issues

**Comment by deveshprojectwork** [comment]
this issue is closed
